import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//context
import { UserContext } from '../src/contexts/userContext'
import About from './About'
import Test from './Test'

const Home: NextPage = () => {
  const [navigation, setNavigationTo] = useState("")
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header>
          <nav>
            <ul>
              <li onClick={() => { setNavigationTo("about") }}>about</li>
              <li onClick={() => { setNavigationTo("test") }}>test</li>
            </ul>
          </nav>
        </header>

        <UserContext.Provider value="hello from context">
          {navigation === "" && <div> Hello</div>}
          {navigation === "about" && <About />}
          {navigation === "test" && <Test />}
        </UserContext.Provider>

      </main>


    </div>
  )
}

export default Home
